# Form implementation generated from reading ui file 'BrainRing.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from odingamewindow import Ui_odingameWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 500)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        self.new_game = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.new_game.setFont(font)
        self.new_game.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.new_game.setTabletTracking(False)
        self.new_game.setObjectName("new_game")
        self.settings = QtWidgets.QMenu(parent=self.menubar)
        self.settings.setObjectName("settings")
        self.Reference = QtWidgets.QMenu(parent=self.menubar)
        self.Reference.setObjectName("Reference")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.Turnir = QtGui.QAction(parent=MainWindow)
        self.Turnir.setObjectName("Turnir")
        self.odin_game = QtGui.QAction(parent=MainWindow)
        self.odin_game.setObjectName("odin_game")
        self.odin_game.triggered.connect(self.odingamewindow)
        self.turnir = QtGui.QAction(parent=MainWindow)
        self.turnir.setObjectName("turnir")
        self.ruls_game = QtGui.QAction(parent=MainWindow)
        self.ruls_game.setObjectName("ruls_game")
        self.display_set = QtGui.QAction(parent=MainWindow)
        self.display_set.setObjectName("display_set")
        self.how_play = QtGui.QAction(parent=MainWindow)
        self.how_play.setObjectName("how_play")
        self.dev_team = QtGui.QAction(parent=MainWindow)
        self.dev_team.setObjectName("dev_team")
        self.new_game.addAction(self.odin_game)
        self.new_game.addAction(self.turnir)
        self.settings.addAction(self.ruls_game)
        self.settings.addAction(self.display_set)
        self.Reference.addAction(self.how_play)
        self.Reference.addAction(self.dev_team)
        self.menubar.addAction(self.new_game.menuAction())
        self.menubar.addAction(self.settings.menuAction())
        self.menubar.addAction(self.Reference.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BrainRing"))
        self.new_game.setTitle(_translate("MainWindow", "Новая игра"))
        self.settings.setTitle(_translate("MainWindow", "Настройки"))
        self.Reference.setTitle(_translate("MainWindow", "Справка"))
        self.action.setText(_translate("MainWindow", "Одиночная игра"))
        self.action_2.setText(_translate("MainWindow", "Турнир"))
        self.Turnir.setText(_translate("MainWindow", "Турнир"))
        self.odin_game.setText(_translate("MainWindow", "Одиночная игра"))
        self.turnir.setText(_translate("MainWindow", "Турнир"))
        self.ruls_game.setText(_translate("MainWindow", "Правила игры"))
        self.display_set.setText(_translate("MainWindow", "Настройка дисплеев"))
        self.how_play.setText(_translate("MainWindow", "Об игре"))
        self.dev_team.setText(_translate("MainWindow", "О разработчиках"))

    def odingamewindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_odingameWindow()
        self.ui.setupUi(self.window)
        self.window.show()    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
