# Form implementation generated from reading ui file 'TTT_Gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *


class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 504)
        self.pushButton_00 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_00.setGeometry(QtCore.QRect(10, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_00.setFont(font)
        self.pushButton_00.setText("")
        self.pushButton_00.setObjectName("pushButton_00")
        self.pushButton_00.clicked.connect(self.btn_push)
        self.pushButton_01 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_01.setGeometry(QtCore.QRect(130, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_01.setFont(font)
        self.pushButton_01.setText("")
        self.pushButton_01.setObjectName("pushButton_01")
        self.pushButton_01.clicked.connect(self.btn_push)
        self.pushButton_02 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_02.setGeometry(QtCore.QRect(250, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_02.setFont(font)
        self.pushButton_02.setText("")
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_02.clicked.connect(self.btn_push)
        self.pushButton_10 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 130, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.btn_push)
        self.pushButton_11 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 130, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.btn_push)
        self.pushButton_12 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_12.setGeometry(QtCore.QRect(250, 130, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.btn_push)
        self.pushButton_20 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 250, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.btn_push)
        self.pushButton_21 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_21.setGeometry(QtCore.QRect(130, 250, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.clicked.connect(self.btn_push)
        self.pushButton_22 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_22.setGeometry(QtCore.QRect(250, 250, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.clicked.connect(self.btn_push)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 420, 350, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"color:green\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_reset = QtWidgets.QPushButton(parent=Form)
        self.pushButton_reset.setGeometry(QtCore.QRect(130, 370, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setStyleSheet("QPushButton {\n"
"background-color:red\n"
"}\n"
"")
        self.pushButton_reset.setObjectName("pushButton_reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.p1 = 'X'
        self.p2 = 'O'
        self.count = 0
        self.rules = [['00','01','02'], ['10','11','12'], ['20','21','22'], 
                      ['00','10','20'], ['01','11','21'], ['02','12','22'],
                      ['00','11','22'], ['02','11','20']] 
        self.p1_win = []
        self.p2_win = []
        self.winner = ''

        


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Крестики-Нолики"))
        self.pushButton_reset.setText(_translate("Form", "RESET"))
        self.pushButton_reset.clicked.connect(self.reset)


    def get_winner1(self):
        if len(self.p1_win) == 3 and self.p1_win in self.rules:
            self.p1 = 'Крестики'
            return self.p1
        else:
            return None
        
    def get_winner2(self):
        if len(self.p2_win) == 3 and self.p2_win in self.rules:
            self.p2 = 'Нолики'
            return self.p2
        else:
            return None


    def btn_push(self):
        btn = self.sender()
        if self.count % 2 == 0:
            btn.setText(self.p1)
            self.p1_win.append(btn.objectName()[-2:])
            self.count += 1
            if self.count > 4:
                for i in self.rules:
                    new_p = []
                    for j in i:
                        if j in self.p1_win:
                            new_p.append(j)
                    if len(new_p) == 3:
                        self.p1_win = new_p
                        self.p1_win = sorted(self.p1_win)
                        self.winner = self.get_winner1()
                        if self.winner:
                            self.block_buttoms()
                            self.label.setText(f'{self.p1} победили')
        elif self.count % 2 != 0:
            btn.setText(self.p2)
            self.p2_win.append(btn.objectName()[-2:])
            self.count += 1
            if self.count > 5:
                for i in self.rules:
                    new_p = []
                    for j in i:
                        if j in self.p2_win:
                            new_p.append(j)
                    if len(new_p) == 3:
                        self.p2_win = new_p
                        self.p2_win = sorted(self.p2_win)
                        self.winner = self.get_winner2()
                        if self.winner:
                            self.block_buttoms()
                            self.label.setText(f'{self.p2} победили')
        if not self.winner and self.count == 9:
            self.block_buttoms()
            self.label.setText('У вас ничья')

    def block_buttoms(self):
        self.pushButton_00.setEnabled(False)
        self.pushButton_01.setEnabled(False)
        self.pushButton_02.setEnabled(False)
        self.pushButton_10.setEnabled(False)
        self.pushButton_11.setEnabled(False)
        self.pushButton_12.setEnabled(False)
        self.pushButton_20.setEnabled(False)
        self.pushButton_21.setEnabled(False)
        self.pushButton_22.setEnabled(False)


    def unblock_buttoms(self):
        self.pushButton_00.setEnabled(True)
        self.pushButton_01.setEnabled(True)
        self.pushButton_02.setEnabled(True)
        self.pushButton_10.setEnabled(True)
        self.pushButton_11.setEnabled(True)
        self.pushButton_12.setEnabled(True)
        self.pushButton_20.setEnabled(True)
        self.pushButton_21.setEnabled(True)
        self.pushButton_22.setEnabled(True)


    def reset(self):
        self.unblock_buttoms()
        self.p1 = 'X'
        self.p2 = 'O'
        self.count = 0
        self.p1_win = []
        self.p2_win = []
        self.winner = ''
        self.pushButton_00.setText('')
        self.pushButton_01.setText('')
        self.pushButton_02.setText('')
        self.pushButton_10.setText('')
        self.pushButton_11.setText('')
        self.pushButton_12.setText('')
        self.pushButton_20.setText('')
        self.pushButton_21.setText('')
        self.pushButton_22.setText('')

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
